### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by ank1traj** [rtCamp/rtbiz#87] opened 2022-01-28 04:26 UTC
### Environment
**OS** - Windows
**Browser** - Chrome
**Architecture** - x64
**WordPress Version** - 5.9

| name  | About  | labels  | assignees|
|---|---|---|---|
|  🐛 Bug Report | PHP error🤔. | bug  |   |

**Description** - PHP error - Creating default object from empty value

**Expected** - There should be no error message 

**Screenshot** - 
![image](https://user-images.githubusercontent.com/32160084/151487130-66367928-3ad9-4389-8347-328837047b87.png)

**Comment by ank1traj** [comment] 2022-02-01 06:17
Hi @delowardev 

This issue has been fixed. You can merge the code with master branch. 

cc: @pooja-muchandikar

**Comment by pooja-muchandikar** [comment] 2022-02-01 06:18
No wait, there is no develop branch?

**Comment by ank1traj** [comment] 2022-02-01 06:23
@pooja-muchandikar There is a develop branch.

**Comment by pooja-muchandikar** [comment] 2022-02-01 06:53
@delowardev 

Please create PR first for develop branch

**Comment by delowardev** [comment] 2022-02-01 07:26
@pooja-muchandikar This issue is only available in the master branch; also that file (where the error comes from) is not available in the develop branch.

**Comment by pooja-muchandikar** [comment] 2022-02-01 07:30
Ok in this case its fine, I will wait for sometime for the PR to get reviewed & then get this merged in master.

**Comment by pooja-muchandikar** [comment] 2022-02-09 05:48
Closing this issue as the issue is fixed & released in v1.4.4

**Closed by pooja-muchandikar** 2022-02-09 05:48 UTC
